### ISSUE TITLE
ImportError: cannot import name 'MidpointSolver'

### ISSUE THREAD

**Issue by yaomz16** [tksmatsubara/symplectic-adjoint-method#1]
Hi, I'm trying to use this package and encountered the following problem:

>>> from torch_symplectic_adjoint import symplectic_adjoint

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/jet/home/mingzeya/tools/symplectic-adjoint-method/torch_symplectic_adjoint/__init__.py", line 1, in <module>
    from ._impl import odeint
  File "/jet/home/mingzeya/tools/symplectic-adjoint-method/torch_symplectic_adjoint/_impl/__init__.py", line 1, in <module>
    from .odeint import odeint
  File "/jet/home/mingzeya/tools/symplectic-adjoint-method/torch_symplectic_adjoint/_impl/odeint.py", line 10, in <module>
    from .integrators.midpoint import MidpointSolver
ImportError: cannot import name 'MidpointSolver' from 'torch_symplectic_adjoint._impl.integrators.midpoint' (/jet/home/mingzeya/tools/symplectic-adjoint-method/torch_symplectic_adjoint/_impl/integrators/midpoint.py)

Is there circular dependency existing in the package?

**Comment by tksmatsubara** [comment]
Thank you for your comment. This is due to a typo I made when I refactored the code for the release.

> MidpointSolver -> MidPointSolver

In addition, I found other typos in the class names to be imported.

> symplectic_adjoint -> odeint_symplectic_adjoint

I fixed the typos in the latest commit. Could you please retry our code? Sorry for the inconvenience.

**Comment by yaomz16** [comment]
Thanks so much for fixing this issue, the function can now be imported properly.
